### ISSUE TITLE
프로젝트 셋업

### ISSUE THREAD

**Issue by blockmonkey1992** [Blockchain-Lighthouse/SmartAuction_BE#4]
**Tasks**
- [x]  CORS 셋팅
- [x] Validation Pipe 적용
- [x] Err Filter 적용
- [x]  Database 연결 (MariaDB)
- [x]  TypeORM 셋팅
- [ ]  Redis 연결
- [x]  환경변수처리
- [x]  Entity 정의
- [x]  Github 셋팅
- [x]  Swagger 적용
- [ ] Entity 작성
